// <auto-generated />
using System;
using ITIDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITIDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318090738_changeDepartmentFK")]
    partial class changeDepartmentFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITIDB.Models.Course", b =>
                {
                    b.Property<int>("Crs_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Crs_id"));

                    b.Property<string>("Crs_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Duration")
                        .HasColumnType("datetime2");

                    b.Property<int>("Top_id")
                        .HasColumnType("int");

                    b.HasKey("Crs_id");

                    b.HasIndex("Top_id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("ITIDB.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dept_ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Manager_hiredate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dept_ManagerId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("ITIDB.Models.Ins_Course", b =>
                {
                    b.Property<int>("Crs_Id")
                        .HasColumnType("int");

                    b.Property<int>("st_Id")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.HasKey("Crs_Id", "st_Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("st_Id");

                    b.ToTable("Ins_Course");
                });

            modelBuilder.Entity("ITIDB.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("deptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("deptId");

                    b.ToTable("Instructor");
                });

            modelBuilder.Entity("ITIDB.Models.Std_Course", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Std_Course");
                });

            modelBuilder.Entity("ITIDB.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("St_super")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("St_super");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("ITIDB.Models.Topic", b =>
                {
                    b.Property<int>("Top_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Top_Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Top_Id");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("ITIDB.Models.Course", b =>
                {
                    b.HasOne("ITIDB.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("Top_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ITIDB.Models.Department", b =>
                {
                    b.HasOne("ITIDB.Models.Instructor", "Dept_Manager")
                        .WithMany("DepartmentManaged")
                        .HasForeignKey("Dept_ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dept_Manager");
                });

            modelBuilder.Entity("ITIDB.Models.Ins_Course", b =>
                {
                    b.HasOne("ITIDB.Models.Course", "Course")
                        .WithMany("Ins_Courses")
                        .HasForeignKey("Crs_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIDB.Models.Instructor", null)
                        .WithMany("Ins_Courses")
                        .HasForeignKey("InstructorId");

                    b.HasOne("ITIDB.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("st_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITIDB.Models.Instructor", b =>
                {
                    b.HasOne("ITIDB.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("deptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITIDB.Models.Std_Course", b =>
                {
                    b.HasOne("ITIDB.Models.Course", "Course")
                        .WithMany("Std_Courses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIDB.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITIDB.Models.Student", b =>
                {
                    b.HasOne("ITIDB.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ITIDB.Models.Student", "Super")
                        .WithMany("StudentsSupervised")
                        .HasForeignKey("St_super")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Super");
                });

            modelBuilder.Entity("ITIDB.Models.Course", b =>
                {
                    b.Navigation("Ins_Courses");

                    b.Navigation("Std_Courses");
                });

            modelBuilder.Entity("ITIDB.Models.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("ITIDB.Models.Instructor", b =>
                {
                    b.Navigation("DepartmentManaged");

                    b.Navigation("Ins_Courses");
                });

            modelBuilder.Entity("ITIDB.Models.Student", b =>
                {
                    b.Navigation("StudentsSupervised");
                });
#pragma warning restore 612, 618
        }
    }
}
